# Generated by Django 4.2.7 on 2023-11-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappInner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='details',
            field=models.CharField(default='asd', max_length=500),
        ),
        migrations.AddField(
            model_name='feature',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(default='cualsea', max_length=40),
        ),
    ]
